#pragma once

#include <Skyrim.h>
#include <Skyrim/ExtraData/ExtraDataTypes.h>
#include <Skyrim/ExtraData/BSExtraData.h>
#include <Skyrim/ExtraData/ExtraActivateRefChildren.h>
#include <Skyrim/ExtraData/ExtraAliasInstanceArray.h>
#include <Skyrim/ExtraData/ExtraAshPileRef.h>
#include <Skyrim/ExtraData/ExtraCannotWear.h>
#include <Skyrim/ExtraData/ExtraCharge.h>
#include <Skyrim/ExtraData/ExtraCollisionData.h>
#include <Skyrim/ExtraData/ExtraContainerChanges.h>
#include <Skyrim/ExtraData/ExtraCount.h>
#include <Skyrim/ExtraData/ExtraDroppedItemList.h>
#include <Skyrim/ExtraData/ExtraEditorID.h>
#include <Skyrim/ExtraData/ExtraEnableStateParent.h>
#include <Skyrim/ExtraData/ExtraEnchantment.h>
#include <Skyrim/ExtraData/ExtraEncounterZone.h>
#include <Skyrim/ExtraData/ExtraFactionChanges.h>
#include <Skyrim/ExtraData/ExtraFlags.h>
#include <Skyrim/ExtraData/ExtraFollower.h>
#include <Skyrim/ExtraData/ExtraFollowerSwimBreadcrumbs.h>
#include <Skyrim/ExtraData/ExtraForcedTarget.h>
#include <Skyrim/ExtraData/ExtraHealth.h>
#include <Skyrim/ExtraData/ExtraHotkey.h>
#include <Skyrim/ExtraData/ExtraInteraction.h>
#include <Skyrim/ExtraData/ExtraItemDropper.h>
#include <Skyrim/ExtraData/ExtraLightData.h>
#include <Skyrim/ExtraData/ExtraLinkedRef.h>
#include <Skyrim/ExtraData/ExtraLinkedRefChildren.h>
#include <Skyrim/ExtraData/ExtraLocation.h>
#include <Skyrim/ExtraData/ExtraLocationRefType.h>
#include <Skyrim/ExtraData/ExtraLock.h>
#include <Skyrim/ExtraData/ExtraMagicCaster.h>
#include <Skyrim/ExtraData/ExtraMapMarker.h>
#include <Skyrim/ExtraData/ExtraOutfitItem.h>
#include <Skyrim/ExtraData/ExtraOwnership.h>
#include <Skyrim/ExtraData/ExtraPersistentCell.h>
#include <Skyrim/ExtraData/ExtraPoison.h>
#include <Skyrim/ExtraData/ExtraPrimitive.h>
#include <Skyrim/ExtraData/ExtraPromotedRef.h>
#include <Skyrim/ExtraData/ExtraReferenceHandle.h>
#include <Skyrim/ExtraData/ExtraSayTopicInfo.h>
#include <Skyrim/ExtraData/ExtraScale.h>
#include <Skyrim/ExtraData/ExtraSoul.h>
#include <Skyrim/ExtraData/ExtraStartingPosition.h>
#include <Skyrim/ExtraData/ExtraTextDisplayData.h>
#include <Skyrim/ExtraData/ExtraTimeLeft.h>
#include <Skyrim/ExtraData/ExtraWorn.h>
#include <Skyrim/ExtraData/ExtraWornLeft.h>
#include <Skyrim/ExtraData/NonActorMagicCaster.h>
#include <Skyrim/ExtraData/NonActorMagicTarget.h>
