#pragma once

#include <Skyrim.h>
#include <Skyrim/Forms/TESObject.h>
#include <Skyrim/Forms/TESBoundObject.h>
#include <Skyrim/Forms/BGSAcousticSpace.h>
#include <Skyrim/Forms/BGSAddonNode.h>
#include <Skyrim/Forms/BGSArtObject.h>
//#include <Skyrim/Forms/BGSCloudClusterForm.h>		// deleted
#include <Skyrim/Forms/BGSDualCastData.h>
#include <Skyrim/Forms/BGSExplosion.h>
#include <Skyrim/Forms/BGSHazard.h>
#include <Skyrim/Forms/BGSIdleMarker.h>
#include <Skyrim/Forms/BGSNote.h>
#include <Skyrim/Forms/BGSProjectile.h>
#include <Skyrim/Forms/BGSStaticCollection.h>
#include <Skyrim/Forms/MagicItem.h>
#include <Skyrim/Forms/AlchemyItem.h>
#include <Skyrim/Forms/EnchantmentItem.h>
#include <Skyrim/Forms/IngredientItem.h>
#include <Skyrim/Forms/SpellItem.h>
#include <Skyrim/Forms/ScrollItem.h>
#include <Skyrim/Forms/TESAmmo.h>
#include <Skyrim/Forms/TESBoundAnimObject.h>
#include <Skyrim/Forms/TESActorBase.h>
#include <Skyrim/Forms/TESNPC.h>
#include <Skyrim/Forms/TESLevCharacter.h>
#include <Skyrim/Forms/TESObjectACTI.h>
#include <Skyrim/Forms/BGSTalkingActivator.h>
#include <Skyrim/Forms/TESFlora.h>
#include <Skyrim/Forms/TESFurniture.h>
#include <Skyrim/Forms/TESObjectCONT.h>
#include <Skyrim/Forms/TESObjectDOOR.h>
#include <Skyrim/Forms/TESObjectLIGH.h>
#include <Skyrim/Forms/TESSound.h>
#include <Skyrim/Forms/TESGrass.h>
#include <Skyrim/Forms/TESLevItem.h>
#include <Skyrim/Forms/TESLevSpell.h>
#include <Skyrim/Forms/TESObjectARMO.h>
#include <Skyrim/Forms/TESObjectBOOK.h>
#include <Skyrim/Forms/TESObjectMISC.h>
#include <Skyrim/Forms/BGSApparatus.h>
#include <Skyrim/Forms/TESKey.h>
#include <Skyrim/Forms/TESSoulGem.h>
#include <Skyrim/Forms/TESObjectSTAT.h>
#include <Skyrim/Forms/BGSMovableStatic.h>
#include <Skyrim/Forms/TESObjectTREE.h>
#include <Skyrim/Forms/TESObjectWEAP.h>
#include <Skyrim/Forms/TESObjectARMA.h>
#include <Skyrim/Forms/ActiveEffect.h>
