#pragma once

#include <Skyrim.h>
#include <Skyrim/Forms/TESForm.h>
#include <Skyrim/Forms/ActorValueInfo.h>
#include <Skyrim/Forms/BGSAssociationType.h>
#include <Skyrim/Forms/BGSBodyPartData.h>
#include <Skyrim/Forms/BGSCameraPath.h>
#include <Skyrim/Forms/BGSCameraShot.h>
#include <Skyrim/Forms/BGSCollisionLayer.h>
#include <Skyrim/Forms/BGSColorForm.h>
#include <Skyrim/Forms/BGSConstructibleObject.h>
#include <Skyrim/Forms/BGSDebris.h>
#include <Skyrim/Forms/BGSDefaultObjectManager.h>
#include <Skyrim/Forms/BGSDialogueBranch.h>
#include <Skyrim/Forms/BGSEncounterZone.h>
#include <Skyrim/Forms/BGSEquipSlot.h>
#include <Skyrim/Forms/BGSFootstep.h>
#include <Skyrim/Forms/BGSFootstepSet.h>
#include <Skyrim/Forms/BGSHeadPart.h>
#include <Skyrim/Forms/BGSImpactData.h>
#include <Skyrim/Forms/BGSImpactDataSet.h>
#include <Skyrim/Forms/BGSKeyword.h>
#include <Skyrim/Forms/BGSAction.h>
#include <Skyrim/Forms/BGSLocationRefType.h>
#include <Skyrim/Forms/BGSLightingTemplate.h>
#include <Skyrim/Forms/BGSListForm.h>
#include <Skyrim/Forms/BGSLocation.h>
#include <Skyrim/Forms/BGSMaterialObject.h>
#include <Skyrim/Forms/BGSMaterialType.h>
#include <Skyrim/Forms/BGSMenuIcon.h>
#include <Skyrim/Forms/BGSMessage.h>
#include <Skyrim/Forms/BGSMovementType.h>
#include <Skyrim/Forms/BGSMusicTrackFormWrapper.h>
#include <Skyrim/Forms/BGSMusicType.h>
#include <Skyrim/Forms/BGSOutfit.h>
#include <Skyrim/Forms/BGSPerk.h>
#include <Skyrim/Forms/BGSRagdoll.h>
#include <Skyrim/Forms/BGSReferenceEffect.h>
#include <Skyrim/Forms/BGSRelationship.h>
#include <Skyrim/Forms/BGSReverbParameters.h>
#include <Skyrim/Forms/BGSScene.h>
#include <Skyrim/Forms/BGSShaderParticleGeometryData.h>
#include <Skyrim/Forms/BGSSoundCategory.h>
#include <Skyrim/Forms/BGSSoundDescriptorForm.h>
#include <Skyrim/Forms/BGSSoundOutput.h>
#include <Skyrim/Forms/BGSRefAlias.h>
#include <Skyrim/Forms/BGSLocAlias.h>
#include <Skyrim/Forms/TESQuest.h>
#include <Skyrim/Forms/BGSVoiceType.h>
#include <Skyrim/Forms/EffectSetting.h>
#include <Skyrim/Forms/NavMesh.h>
#include <Skyrim/Forms/NavMeshInfoMap.h>
#include <Skyrim/Forms/Script.h>
#include <Skyrim/Forms/TESClass.h>
#include <Skyrim/Forms/TESClimate.h>
#include <Skyrim/Forms/TESCombatStyle.h>
#include <Skyrim/Forms/TESEffectShader.h>
#include <Skyrim/Forms/TESEyes.h>
#include <Skyrim/Forms/TESFaction.h>
#include <Skyrim/Forms/TESGlobal.h>
//#include <Skyrim/Forms/TESHair.h>			// deleted
#include <Skyrim/Forms/TESIdleForm.h>
#include <Skyrim/Forms/TESImageSpace.h>
#include <Skyrim/Forms/TESImageSpaceModifier.h>
#include <Skyrim/Forms/TESLandTexture.h>
#include <Skyrim/Forms/TESLoadScreen.h>
#include <Skyrim/Forms/TESObjectANIO.h>
#include <Skyrim/Forms/TESObjectCELL.h>
#include <Skyrim/Forms/TESObjectLAND.h>
#include <Skyrim/Forms/TESPackage.h>
#include <Skyrim/Forms/TESRace.h>
#include <Skyrim/Forms/TESShout.h>
#include <Skyrim/Forms/TESTopic.h>
#include <Skyrim/Forms/TESTopicInfo.h>
#include <Skyrim/Forms/TESWaterForm.h>
#include <Skyrim/Forms/TESWeather.h>
#include <Skyrim/Forms/TESWordOfPower.h>
#include <Skyrim/Forms/TESWorldSpace.h>
#include <Skyrim/Radiant Story/BGSStoryManagerTreeForm.h>
#include <Skyrim/Radiant Story/BGSStoryManagerNodeBase.h>
#include <Skyrim/Radiant Story/BGSStoryManagerBranchNode.h>
#include <Skyrim/Radiant Story/BGSStoryManagerEventNode.h>
#include <Skyrim/Radiant Story/BGSStoryManagerQuestNode.h>
#include <Skyrim/Regions/TESRegion.h>
