#pragma once

#include <Skyrim.h>
#include <Skyrim/TESForms/Gameplay/TESSound.h>
#include <Skyrim/TESForms/Gameplay/BGSAcousticSpace.h>
#include <Skyrim/TESForms/Character/BGSIdleMarker.h>
#include <Skyrim/TESForms/Character/BGSNote.h>
#include <Skyrim/TESForms/Character/TESActorBase.h>
#include <Skyrim/TESForms/Character/TESNPC.h>
#include <Skyrim/TESForms/Objects/TESObject.h>
#include <Skyrim/TESForms/Objects/TESBoundObject.h>
#include <Skyrim/TESForms/Objects/BGSAddonNode.h>
#include <Skyrim/TESForms/Objects/BGSArtObject.h>
//#include <Skyrim/TESForms/Objects/BGSCloudClusterForm.h>		// deleted
#include <Skyrim/TESForms/Objects/BGSExplosion.h>
#include <Skyrim/TESForms/Objects/BGSHazard.h>
#include <Skyrim/TESForms/Objects/BGSProjectile.h>
#include <Skyrim/TESForms/Objects/BGSStaticCollection.h>
#include <Skyrim/TESForms/Objects/TESAmmo.h>
#include <Skyrim/TESForms/Objects/TESBoundAnimObject.h>
#include <Skyrim/TESForms/Objects/TESLevCharacter.h>
#include <Skyrim/TESForms/Objects/TESObjectACTI.h>
#include <Skyrim/TESForms/Objects/BGSTalkingActivator.h>
#include <Skyrim/TESForms/Objects/TESFlora.h>
#include <Skyrim/TESForms/Objects/TESFurniture.h>
#include <Skyrim/TESForms/Objects/TESObjectCONT.h>
#include <Skyrim/TESForms/Objects/TESObjectDOOR.h>
#include <Skyrim/TESForms/Objects/TESObjectLIGH.h>
#include <Skyrim/TESForms/Objects/TESGrass.h>
#include <Skyrim/TESForms/Objects/TESLevItem.h>
#include <Skyrim/TESForms/Objects/TESLevSpell.h>
#include <Skyrim/TESForms/Objects/TESObjectARMO.h>
#include <Skyrim/TESForms/Objects/TESObjectBOOK.h>
#include <Skyrim/TESForms/Objects/TESObjectMISC.h>
#include <Skyrim/TESForms/Objects/TESKey.h>
#include <Skyrim/TESForms/Objects/TESSoulGem.h>
#include <Skyrim/TESForms/Objects/TESObjectSTAT.h>
#include <Skyrim/TESForms/Objects/BGSMovableStatic.h>
#include <Skyrim/TESForms/Objects/TESObjectTREE.h>
#include <Skyrim/TESForms/Objects/TESObjectWEAP.h>
#include <Skyrim/TESForms/Objects/TESObjectARMA.h>
#include <Skyrim/TESForms/Objects/BGSApparatus.h>
#include <Skyrim/Magic/ActiveEffect.h>
#include <Skyrim/Magic/BGSDualCastData.h>
#include <Skyrim/Magic/MagicItem.h>
#include <Skyrim/Magic/AlchemyItem.h>
#include <Skyrim/Magic/EnchantmentItem.h>
#include <Skyrim/Magic/IngredientItem.h>
#include <Skyrim/Magic/SpellItem.h>
#include <Skyrim/Magic/ScrollItem.h>
