#pragma once

#include <Skyrim.h>

#include <Skyrim/FormComponents/BaseFormComponent.h>
#include <Skyrim/FormComponents/ActorValueOwner.h>
#include <Skyrim/FormComponents/BGSAttackDataForm.h>
#include <Skyrim/FormComponents/BGSBipedObjectForm.h>
#include <Skyrim/FormComponents/BGSBlockBashData.h>
#include <Skyrim/FormComponents/BGSDestructibleObjectForm.h>
#include <Skyrim/FormComponents/BGSEquipType.h>
#include <Skyrim/FormComponents/BGSIdleCollection.h>
#include <Skyrim/FormComponents/BGSKeywordForm.h>
#include <Skyrim/FormComponents/BGSMenuDisplayObject.h>
#include <Skyrim/FormComponents/BGSMessageIcon.h>
#include <Skyrim/FormComponents/BGSOpenCloseForm.h>
#include <Skyrim/FormComponents/BGSOverridePackCollection.h>
#include <Skyrim/FormComponents/BGSPerkRankArray.h>
#include <Skyrim/FormComponents/BGSPickupPutdownSounds.h>
#include <Skyrim/FormComponents/BGSPreloadable.h>
#include <Skyrim/FormComponents/BGSSkillPerkTreeNode.h>
#include <Skyrim/FormComponents/BGSSkinForm.h>
#include <Skyrim/FormComponents/BGSSoundDescriptor.h>
#include <Skyrim/FormComponents/TESActorBaseData.h>
#include <Skyrim/FormComponents/TESAIForm.h>
#include <Skyrim/FormComponents/TESAttackDamageForm.h>
#include <Skyrim/FormComponents/TESBipedModelForm.h>
#include <Skyrim/FormComponents/TESContainer.h>
#include <Skyrim/FormComponents/TESDescription.h>
#include <Skyrim/FormComponents/TESEnchantableForm.h>
#include <Skyrim/FormComponents/TESFullName.h>
#include <Skyrim/FormComponents/TESImageSpaceModifiableForm.h>
#include <Skyrim/FormComponents/TESLeveledList.h>
#include <Skyrim/FormComponents/TESProduceForm.h>
#include <Skyrim/FormComponents/TESQualityForm.h>
#include <Skyrim/FormComponents/TESRaceForm.h>
#include <Skyrim/FormComponents/TESReactionForm.h>
#include <Skyrim/FormComponents/TESSpellList.h>
#include <Skyrim/FormComponents/TESValueForm.h>
#include <Skyrim/FormComponents/TESWeightForm.h>

/// TESTexture
#include <Skyrim/FormComponents/TESTexture.h>
#include <Skyrim/FormComponents/TESIcon.h>
#include <Skyrim/FormComponents/TESTexture1024.h>

/// TESModel
#include <Skyrim/FormComponents/TESModel.h>
#include <Skyrim/FormComponents/BGSBehaviorGraphModel.h>
#include <Skyrim/FormComponents/BGSTextureModel.h>
#include <Skyrim/FormComponents/TESModelPSA.h>
#include <Skyrim/FormComponents/TESModelRDT.h>
#include <Skyrim/FormComponents/TESModelTextureSwap.h>
#include <Skyrim/FormComponents/TESModelTri.h>

/// not child of BaseComponent
#include <Skyrim/FormComponents/BSMaterialObject.h>
#include <Skyrim/FormComponents/Condition.h>
#include <Skyrim/FormComponents/TESChildCell.h>
#include <Skyrim/FormComponents/TintMask.h>
#include <Skyrim/Regions/TESRegionData.h>
#include <Skyrim/Regions/TESRegionDataGrass.h>
#include <Skyrim/Regions/TESRegionDataLandscape.h>
#include <Skyrim/Regions/TESRegionDataMap.h>
#include <Skyrim/Regions/TESRegionDataSound.h>
#include <Skyrim/Regions/TESRegionDataWeather.h>
#include <Skyrim/Regions/TESRegionGrassObject.h>
#include <Skyrim/Regions/TESRegionGrassObjectList.h>
#include <Skyrim/Regions/TESRegionList.h>
